### ISSUE TITLE
Can't paste password into auth form

### ISSUE THREAD

**Issue by rex** [jenslind/minira#15]
Is this an electron bug? Or is this a deliberate setting in Minira? Using 1Password allows me to create secure passwords for every service I use, which means that they're extremely long and extremely difficult to type one character at a time. 

This is a dealbreaker for me, hopefully this is a bug. This looks like a really useful application.

**Comment by jenslind** [comment]
Yeah, we need an application menu for the copy paste commands to work.

**Comment by jenslind** [comment]
Fixed in `1.0.1`

**Comment by rex** [comment]
@jenslind Awesome! I'll check it out shortly!
